# TwerkingForTrees configuration file. {$version}
# 
# How many times the player must twerk before the tree start growing faster.
# If the player has not twerked enough, then the tree will not grow faster.
minimum-twerks: 4
# Hold to twerk. Accessibility feature. Instead of hitting the crouch button continuously, hold it down.
hold-for-twerk: false
# Use sprinting to grow trees instead of twerking.
sprint-to-grow: false
# Range to look for saplings when twerking. A range of 5 will look +/- 5 blocks in all directions around the player
# Making this too big will lag your server.
range: 5
sounds:
  # Toggle on/off the sounds.
  enabled: true
  twerk:
    # Sound that plays when the player twerked enough for the sapling to start growing faster.
    # Available sounds are the following:
    #    https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    sound: BLOCK_NOTE_BLOCK_BASS
    volume: 1.0
    pitch: 2.0
  growing-small-tree:
    # Sound that plays when a small tree (1x1) grows.
    # Available sounds are the following:
    #    https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    sound: BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT
    volume: 1.0
    pitch: 1.0
  growing-big-tree:
    # Sound that plays when a big tree (2x2) grows.
    # Available sounds are the following:
    #    https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    sound: BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT
    volume: 1.0
    pitch: 1.0
effects:
  # Toggle on/off the particle effects.
  enabled: true
  # Effect that plays each time the player twerks.
  # Available effects are the following:
  #    https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
  twerk: MOBSPAWNER_FLAMES
