# TwerkingForTrees configuration file.
#
# How many times the player must twerk before the tree start growing faster.
# If the player has not twerked enough, then the tree will not grow faster.
minimum-twerks: 4
# Range to look for saplings when twerking. A range of 5 will look +/- 5 blocks in all directions around the player
# Making this too big will lag your server.
range: 5
sounds:
  # Toggle on/off the sounds.
  enabled: true
  twerk:
    # Sound that plays when the player twerked enough for the sapling to start growing faster.
    # Available sounds are the following:
    #    https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    sound: BLOCK_NOTE_BLOCK_BASS
    volume: 1.0
    pitch: 2.0
